"""Hard-coded mapping of every issuer_name in the corpus to country metadata.

261 distinct issuer names. Many are the same country with different formatting.
Corporate/non-sovereign issuers are flagged with is_sovereign=False.

Format: issuer_name -> (country_code, country_name, is_sovereign)
"""

# (country_code, country_name, is_sovereign)
ISSUER_TO_COUNTRY: dict[str, tuple[str, str, bool]] = {
    # --- High volume (>100 docs) ---
    "ISRAEL, STATE OF": ("ISR", "Israel", True),
    "BANK OF CYPRUS HOLDINGS PUBLIC LIMITED COMPANY, BANK OF CYPRUS PUBLIC COMPANY LIMITED (2 issuers)": (
        "CYP",
        "Cyprus",
        False,
    ),
    "FEDERATIVE REPUBLIC OF BRAZIL": ("BRA", "Brazil", True),
    "UNICREDIT S.P.A., UNICREDIT BANK IRELAND PUBLIC LIMITED COMPANY, UNICREDIT INTERNATIONAL BANK (LUXEMBOURG) S.A. (3 issuers)": (
        "ITA",
        "Italy",
        False,
    ),
    "REPUBLIC OF TURKEY": ("TUR", "Turkey", True),
    "UNITED MEXICAN STATES": ("MEX", "Mexico", True),
    "REPUBLIC OF COLOMBIA": ("COL", "Colombia", True),
    "PHILIPPINES (REPUBLIC OF THE)": ("PHL", "Philippines", True),
    "LEBANESE REPUBLIC (THE)": ("LBN", "Lebanon", True),
    "COLOMBIA (REPUBLIC OF)": ("COL", "Colombia", True),
    "T\u00dcRKIYE (THE REPUBLIC OF)": ("TUR", "Turkey", True),
    "REPUBLIC OF CHILE": ("CHL", "Chile", True),
    "UNICREDIT S.P.A., UNICREDIT BANK IRELAND PUBLIC LIMITED COMPANY (2 issuers)": (
        "ITA",
        "Italy",
        False,
    ),
    "BANK OF CYPRUS PUBLIC COMPANY LIMITED": ("CYP", "Cyprus", False),
    "REPUBLIC OF THE PHILIPPINES": ("PHL", "Philippines", True),
    "LATVIA (REPUBLIC OF)": ("LVA", "Latvia", True),
    "UNICREDIT BANK IRELAND PUBLIC LIMITED COMPANY": ("IRL", "Ireland", False),
    "URUGUAY REPUBLIC OF": ("URY", "Uruguay", True),
    "ITALY (REPUBLIC OF)": ("ITA", "Italy", True),
    "URUGUAY (REPUBLICA ORIENTAL DEL)": ("URY", "Uruguay", True),
    "Peru": ("PER", "Peru", True),
    "PANAMA REPUBLIC OF": ("PAN", "Panama", True),
    "OPUS (PUBLIC) CHARTERED ISSUANCE SA": ("LUX", "Luxembourg", False),
    "ARK\u00c9A PUBLIC SECTOR SCF": ("FRA", "France", False),
    "LITHUANIA (THE REPUBLIC OF)": ("LTU", "Lithuania", True),
    "UNICREDIT BANK CZECH REPUBLIC AND SLOVAKIA, A.S.": ("CZE", "Czech Republic", False),
    "PANAMA (THE REPUBLIC OF)": ("PAN", "Panama", True),
    "ARGENTINA (THE REPUBLIC OF)": ("ARG", "Argentina", True),
    "PERU (THE REPUBLIC OF)": ("PER", "Peru", True),
    "Republic of Indonesia": ("IDN", "Indonesia", True),
    "POLAND (THE REPUBLIC OF)": ("POL", "Poland", True),
    "State of Israel": ("ISR", "Israel", True),
    "PERU REPUBLIC OF": ("PER", "Peru", True),
    "CHILE (REPUBLIC OF)": ("CHL", "Chile", True),
    "SOUTH AFRICA (REPUBLIC OF)": ("ZAF", "South Africa", True),
    "AUSTRIA (REPUBLIC OF)": ("AUT", "Austria", True),
    "REPUBLIC OF SOUTH AFRICA": ("ZAF", "South Africa", True),
    "Kingdom of Sweden": ("SWE", "Sweden", True),
    "CANADA": ("CAN", "Canada", True),
    "DOMINICAN REPUBLIC (THE)": ("DOM", "Dominican Republic", True),
    "VENEZUELA (BOLIVARIAN REPUBLIC OF)": ("VEN", "Venezuela", True),
    "ARKEA PUBLIC SECTOR SCF": ("FRA", "France", False),
    "ALDBURG PUBLIC S.A.": ("LUX", "Luxembourg", False),
    "ECUADOR (REPUBLIC OF)": ("ECU", "Ecuador", True),
    "REPUBLIC OF KOREA": ("KOR", "Korea", True),
    "Rwanda": ("RWA", "Rwanda", True),
    "Philippines": ("PHL", "Philippines", True),
    "PROXIMUS S.A. DE DROIT PUBLIC": ("BEL", "Belgium", False),
    "FRESENIUS FINANCE IRELAND PUBLIC LIMITED COMPANY, FRESENIUS SE & CO. KGAA, FRESENIUS FINANCE IRELAND II PUBLIC LIMITED COMPANY (3 issuers)": (
        "DEU",
        "Germany",
        False,
    ),
    "CYPRUS POPULAR BANK PUBLIC CO LTD": ("CYP", "Cyprus", False),
    "ITALY REPUBLIC OF": ("ITA", "Italy", True),
    "FRESENIUS FINANCE IRELAND II PUBLIC LIMITED COMPANY, FRESENIUS FINANCE IRELAND PUBLIC LIMITED COMPANY, FRESENIUS SE & CO KGAA (3 issuers)": (
        "DEU",
        "Germany",
        False,
    ),
    "JAMAICA GOVERNMENT OF": ("JAM", "Jamaica", True),
    "Venezuela": ("VEN", "Venezuela", True),
    "REPUBLIC OF ARGENTINA": ("ARG", "Argentina", True),
    "FRESENIUS FINANCE IRELAND PUBLIC LIMITED COMPANY": ("DEU", "Germany", False),
    "The Federal Republic of Nigeria": ("NGA", "Nigeria", True),
    "State Of Israel": ("ISR", "Israel", True),
    "Emirate of Abu Dhabi": ("ARE", "United Arab Emirates", True),
    "SLOVENIA (REPUBLIC OF)": ("SVN", "Slovenia", True),
    "Ecuador": ("ECU", "Ecuador", True),
    "EGYPT (THE ARAB REPUBLIC OF)": ("EGY", "Egypt", True),
    "BULGARIA (REPUBLIC OF)": ("BGR", "Bulgaria", True),
    "BANK OF CYPRUS HOLDINGS PUBLIC LIMITED COMPANY": ("CYP", "Cyprus", False),
    "HUNGARY": ("HUN", "Hungary", True),
    "Republic of Finland": ("FIN", "Finland", True),
    "Ghana": ("GHA", "Ghana", True),
    "SURINAME (REPUBLIC OF)": ("SUR", "Suriname", True),
    "EL SALVADOR (THE REPUBLIC OF)": ("SLV", "El Salvador", True),
    "HYPO PUBLIC FINANCE BANK": ("AUT", "Austria", False),
    "Kenya": ("KEN", "Kenya", True),
    "PARAGUAY (THE REPUBLIC OF)": ("PRY", "Paraguay", True),
    "CROATIA (REPUBLIC OF)": ("HRV", "Croatia", True),
    "Arab Republic of Egypt": ("EGY", "Egypt", True),
    "Netherlands": ("NLD", "Netherlands", True),
    "Republic Of Cyprus": ("CYP", "Cyprus", True),
    "Hungary": ("HUN", "Hungary", True),
    "STATE OF ISRAEL": ("ISR", "Israel", True),
    "OPUS (PUBLIC) CHARTERED ISSUANCE S.A.": ("LUX", "Luxembourg", False),
    "Jamaica": ("JAM", "Jamaica", True),
    "GREECE (THE HELLENIC REPUBLIC)": ("GRC", "Greece", True),
    "HELLENIC BANK PUBLIC COMPANY LIMITED": ("CYP", "Cyprus", False),
    "Indonesia": ("IDN", "Indonesia", True),
    "PORTUGAL (REPUBLIC OF)": ("PRT", "Portugal", True),
    "Saudi Arabia": ("SAU", "Saudi Arabia", True),
    "FRESENIUS FINANCE IRELAND PUBLIC LIMITED COMPANY, FRESENIUS SE & CO KGAA, FRESENIUS FINANCE IRELAND II PUBLIC LIMITED COMPANY (3 issuers)": (
        "DEU",
        "Germany",
        False,
    ),
    "Republic of Kazakhstan": ("KAZ", "Kazakhstan", True),
    "BNP PARIBAS PUBLIC SECTOR SCF": ("FRA", "France", False),
    "Sierra Leone": ("SLE", "Sierra Leone", True),
    "Argentina": ("ARG", "Argentina", True),
    "China": ("CHN", "China", True),
    "TURKEY (REPUBLIC OF)": ("TUR", "Turkey", True),
    "The Republic of Ghana": ("GHA", "Ghana", True),
    "Angola": ("AGO", "Angola", True),
    "GUATEMALA (THE REPUBLIC OF)": ("GTM", "Guatemala", True),
    "HELLENIC RAILWAYS, GREECE (THE HELLENIC REPUBLIC)": ("GRC", "Greece", False),
    "Republic of Iceland": ("ISL", "Iceland", True),
    "Kingdom of Saudi Arabia (The)": ("SAU", "Saudi Arabia", True),
    "LUNAR FUNDING V PUBLIC LIMITED COMPANY": ("IRL", "Ireland", False),
    "Serbia (Republic of)": ("SRB", "Serbia", True),
    "EUROBANK LIMITED": ("CYP", "Cyprus", False),
    "CZECH REPUBLIC": ("CZE", "Czech Republic", True),
    "Nigeria": ("NGA", "Nigeria", True),
    "Uzbekistan (Republic of)": ("UZB", "Uzbekistan", True),
    "Angola (The Republic of)": ("AGO", "Angola", True),
    "State of Qatar-Ministry of Finance": ("QAT", "Qatar", True),
    "Kingdom of Saudi Arabia": ("SAU", "Saudi Arabia", True),
    "Sweden": ("SWE", "Sweden", True),
    "Cyprus": ("CYP", "Cyprus", True),
    "ICELAND (REPUBLIC OF)": ("ISL", "Iceland", True),
    "Cameroon": ("CMR", "Cameroon", True),
    "Government of The Republic of Iceland": ("ISL", "Iceland", True),
    "TRINIDAD AND TOBAGO (REPUBLIC OF)": ("TTO", "Trinidad and Tobago", True),
    "Bahrain": ("BHR", "Bahrain", True),
    "Oman Sovereign Sukuk S.A.O.C.": ("OMN", "Oman", True),
    "CHINA (PEOPLE'S REPUBLIC OF)": ("CHN", "China", True),
    "Kazakhstan": ("KAZ", "Kazakhstan", True),
    "Republic of Serbia (represented by the Government of the Republic of Serbia, acting by and through the Ministry of Finance)": (
        "SRB",
        "Serbia",
        True,
    ),
    "Senegal": ("SEN", "Senegal", True),
    "UNICREDIT BANK GMBH": ("DEU", "Germany", False),
    "BELGACOM FINANCE S.A., PROXIMUS S.A. DE DROIT PUBLIC (2 issuers)": ("BEL", "Belgium", False),
    "AZOR MORTGAGES PUBLIC LIMITED COMPANY": ("IRL", "Ireland", False),
    "Kingdom of Bahrain-Ministry of Fin.": ("BHR", "Bahrain", True),
    "The Republic of Uzbekistan": ("UZB", "Uzbekistan", True),
    "MOL HUNGARIAN OIL AND GAS PUBLIC LIMITED COMPANY": ("HUN", "Hungary", False),
    "Nigeria (Federal Republic of) (The)": ("NGA", "Nigeria", True),
    "SAN MARINO (REPUBLIC OF)": ("SMR", "San Marino", True),
    "COSTA RICA (REPUBLIC OF)": ("CRI", "Costa Rica", True),
    "Republic of Angola": ("AGO", "Angola", True),
    "Barbados": ("BRB", "Barbados", True),
    "PAKISTAN (THE ISLAMIC REPUBLIC OF)": ("PAK", "Pakistan", True),
    "Moldova": ("MDA", "Moldova", True),
    "Egypt (Arab Republic of) (The)": ("EGY", "Egypt", True),
    "UNICREDIT LUXEMBOURG FINANCE S.A., UNICREDIT BANK IRELAND PUBLIC LIMITED COMPANY": (
        "ITA",
        "Italy",
        False,
    ),
    "THE REPUBLIC OF GHANA": ("GHA", "Ghana", True),
    "HONDURAS (THE REPUBLIC OF)": ("HND", "Honduras", True),
    "The Government of the Sultanate of Oman": ("OMN", "Oman", True),
    "Kazakhstan (Republic of)": ("KAZ", "Kazakhstan", True),
    "Kuwait": ("KWT", "Kuwait", True),
    "Republic of Serbia": ("SRB", "Serbia", True),
    "Ethiopia": ("ETH", "Ethiopia", True),
    "SENEGAL (THE REPUBLIC OF)": ("SEN", "Senegal", True),
    "REPUBLIC OF BELARUS": ("BLR", "Belarus", True),
    "BANK OF CYPRUS HOLDINGS PUBLIC LIMITED COMPANY, BANK OF CYPRUS PUBLIC COMPANY LIMITED": (
        "CYP",
        "Cyprus",
        False,
    ),
    "Jordan": ("JOR", "Jordan", True),
    "The Kingdom of Saudi Arabia acting through the Ministry of Finance": (
        "SAU",
        "Saudi Arabia",
        True,
    ),
    "Montenegro": ("MNE", "Montenegro", True),
    "State of Montenegro": ("MNE", "Montenegro", True),
    "Egypt": ("EGY", "Egypt", True),
    "SLOVAK REPUBLIC": ("SVK", "Slovakia", True),
    "SERBIA (THE REPUBLIC OF)": ("SRB", "Serbia", True),
    "Central Bank of Iceland": ("ISL", "Iceland", True),
    "State of Israel Ministry of Finance": ("ISR", "Israel", True),
    "Oman (Government of Sultanate of)": ("OMN", "Oman", True),
    "BELGACOM FINANCE S.A., PROXIMUS S.A. DE DROIT PUBLIC": ("BEL", "Belgium", False),
    "THE ARAB REPUBLIC OF EGYPT": ("EGY", "Egypt", True),
    "Israel": ("ISR", "Israel", True),
    "NATIONAL TREASURY OF THE REPUBLIC OF SOUTH AFRICA": ("ZAF", "South Africa", True),
    "The Hashemite Kingdom of Jordan": ("JOR", "Jordan", True),
    "The Republic Of Uzbekistan": ("UZB", "Uzbekistan", True),
    "FINLAND REPUBLIC OF": ("FIN", "Finland", True),
    "TT&T PUBLIC COMPANY LIMITED": ("THA", "Thailand", False),
    "Sri Lanka (G.D.S. Republic of)": ("LKA", "Sri Lanka", True),
    "Kenya (The Republic of)": ("KEN", "Kenya", True),
    "ALBANIA (THE REPUBLIC OF)": ("ALB", "Albania", True),
    "REPUBLIC OF CONGO (THE)": ("COG", "Republic of Congo", True),
    "SECTEUR PUBLIC FRANCE 2012-1": ("FRA", "France", False),
    "The Govt of the Hong Kong Spl Adm Region of the People's Republic of China": (
        "HKG",
        "Hong Kong",
        True,
    ),
    "Republic of Austria": ("AUT", "Austria", True),
    "Iceland": ("ISL", "Iceland", True),
    "Kyrgyzstan": ("KGZ", "Kyrgyzstan", True),
    "Uzbekistan": ("UZB", "Uzbekistan", True),
    "Ghana (Republic of) (The)": ("GHA", "Ghana", True),
    "Austria": ("AUT", "Austria", True),
    "Republic of Zambia": ("ZMB", "Zambia", True),
    "Kazakhstan Temir Zholy Finance BV": ("KAZ", "Kazakhstan", False),
    "Albania (The Republic of) ": ("ALB", "Albania", True),
    "Government of Canada": ("CAN", "Canada", True),
    "Ukraine, represented by the Minister of Finance": ("UKR", "Ukraine", True),
    "Morocco": ("MAR", "Morocco", True),
    "State of Kuwait (Ministry of Fin.)": ("KWT", "Kuwait", True),
    "State of Montenegro (represented by the Government of Montenegro, acting by and through its Ministry of Finance and Social Welfare)": (
        "MNE",
        "Montenegro",
        True,
    ),
    "Canada": ("CAN", "Canada", True),
    "VIETNAM (THE SOCIALISTIC REPUBLIC OF)": ("VNM", "Vietnam", True),
    "Eastern Republic of Uruguay": ("URY", "Uruguay", True),
    "Joint Stock Company National Bank for Foreign Economic Activity of the Republic of Uzbekistan": (
        "UZB",
        "Uzbekistan",
        False,
    ),
    "Italy": ("ITA", "Italy", True),
    "Brazil": ("BRA", "Brazil", True),
    "Morocco (Kingdom of)": ("MAR", "Morocco", True),
    "THE STANDARD BANK OF SOUTH AFRICA LTD": ("ZAF", "South Africa", False),
    "THE FEDERAL REPUBLIC OF NIGERIA": ("NGA", "Nigeria", True),
    "Emirate Of Abu Dhabi": ("ARE", "United Arab Emirates", True),
    "Jordan (Hashemite Kingdom of) (The)": ("JOR", "Jordan", True),
    "KOREA (THE REPUBLIC OF)": ("KOR", "Korea", True),
    "State Of Kuwait": ("KWT", "Kuwait", True),
    "China (MoF of People's Republic of)": ("CHN", "China", True),
    "Federal Government of UAE": ("ARE", "United Arab Emirates", True),
    "State Of Qatar": ("QAT", "Qatar", True),
    "The State of Qatar": ("QAT", "Qatar", True),
    "South Africa (Government of)": ("ZAF", "South Africa", True),
    "MACEDONIA (FORMER YUGOSLAV REPUBLIC OF)": ("MKD", "North Macedonia", True),
    "Republic of Angola (The)": ("AGO", "Angola", True),
    "Belarus (Republic of)": ("BLR", "Belarus", True),
    "REPUBLIC OF KENYA": ("KEN", "Kenya", True),
    "Zambia (Republic of) (MoF)": ("ZMB", "Zambia", True),
    "Arab Republic of Egypt (The)": ("EGY", "Egypt", True),
    "REPUBLIC OF IRELAND": ("IRL", "Ireland", True),
    "HELLENIC RAILWAYS, GREECE (THE HELLENIC REPUBLIC), NATIONAL BANK OF GREECE S.A.... (7 issuers)": (
        "GRC",
        "Greece",
        False,
    ),
    "JSC National Bank for Foreign Economic Activity of the Republic of Uzbekistan": (
        "UZB",
        "Uzbekistan",
        False,
    ),
    "Republic of  Belarus": ("BLR", "Belarus", True),
    "Government Of The Republic Of Fiji": ("FJI", "Fiji", True),
    "MINISTRY OF FINANCE, THE DEMOCRATIC REPUBLIC OF THE CONGO": (
        "COD",
        "Democratic Republic of the Congo",
        True,
    ),
    "SG ISSUER, SOCIETE GENERALE, PORTUGAL (REPUBLIC OF)": ("FRA", "France", False),
    "The Republic Of Kazakhstan": ("KAZ", "Kazakhstan", True),
    "Arab Republic Of Egypt (The)": ("EGY", "Egypt", True),
    "THE REPUBLIC OF KENYA": ("KEN", "Kenya", True),
    "Global Sukuk Ventures (Q.P.J.S.C.)": ("QAT", "Qatar", False),
    "Bosnia and Herzegovina (Fedtn of.) ": ("BIH", "Bosnia and Herzegovina", True),
    "Republic of Cameroon (The)": ("CMR", "Cameroon", True),
    "National Treasury of the Republic of South Africa": ("ZAF", "South Africa", True),
    "Republic Of Serbia": ("SRB", "Serbia", True),
    "The Republic of Rwanda": ("RWA", "Rwanda", True),
    "GOVERNMENT OF JAMICA": ("JAM", "Jamaica", True),
    "SULTANATE OF OMAN": ("OMN", "Oman", True),
    "Guyana": ("GUY", "Guyana", True),
    "Sri Lanka": ("LKA", "Sri Lanka", True),
    "GOVERNMENT OF BELIZE": ("BLZ", "Belize", True),
    "FINLAND (REPUBLIC OF)": ("FIN", "Finland", True),
    "CASTANEA ONE PUBLIC LIMITED COMPANY": ("IRL", "Ireland", False),
    "UNICREDIT S.P.A., UNICREDIT BANK IRELAND PUBLIC LIMITED COMPANY, ING BANK N.V., UNICREDIT INTERNATIONAL BANK (LUXEMBOURG) S.A.": (
        "ITA",
        "Italy",
        False,
    ),
    "Armenia (Republic of)": ("ARM", "Armenia", True),
    "Gabonese Republic (The)": ("GAB", "Gabon", True),
    "Cyprus (Republic of)": ("CYP", "Cyprus", True),
    "SWEDEN (KINGDOM OF)": ("SWE", "Sweden", True),
    "BANCO DE RESERVAS DE LA REPUBLICA DOMINICANA": ("DOM", "Dominican Republic", False),
    "Uganda": ("UGA", "Uganda", True),
    "ZELEZNICE SLOVENSKEJ REPUBLIKY": ("SVK", "Slovakia", False),
    "XXI CENTURY INVESTMENTS PUBLIC LIMITED": ("CYP", "Cyprus", False),
    "GREECE (THE HELLENIC REPUBLIC), NATIONAL BANK OF GREECE S.A., NBG FINANCE PLC... (25 issuers)": (
        "GRC",
        "Greece",
        False,
    ),
    "REPUBLIC OF TAJIKISTAN": ("TJK", "Tajikistan", True),
    "Albania (The Republic of)": ("ALB", "Albania", True),
    "Srpska (Republic of)": ("BIH", "Bosnia and Herzegovina", True),
    "ESTONIA (REPUBLIC OF)": ("EST", "Estonia", True),
    "MINISTRY OF FINANCE OF REPUBLIC OF SRPSKA": ("BIH", "Bosnia and Herzegovina", True),
    "Latvia": ("LVA", "Latvia", True),
    "MORGAN GUARANTY TRUST COMPANY OF NEW YORK": ("USA", "United States", False),
    "ADVANCE AGRO PUBLIC COMPANY LIMITED": ("THA", "Thailand", False),
    "Serbia": ("SRB", "Serbia", True),
    "Guinea": ("GIN", "Guinea", True),
    "SG ISSUER, PORTUGAL (REPUBLIC OF)": ("FRA", "France", False),
    "Japan": ("JPN", "Japan", True),
    "Bosnia and Herzegovina": ("BIH", "Bosnia and Herzegovina", True),
    "Albania; Andorra; Austria; Indonesia": ("ALB", "Albania", True),
    "THE HASHEMITE KINGDOM OF JORDAN": ("JOR", "Jordan", True),
    "Rwanda (Republic of) (The)": ("RWA", "Rwanda", True),
    "INDONESIA (REPUBLIC OF)": ("IDN", "Indonesia", True),
    "CENTRAL BANK OF THE DOMINICAN REPUBLIC": ("DOM", "Dominican Republic", True),
    "Republic of Uzbekistan": ("UZB", "Uzbekistan", True),
    "Republic of Srpska": ("BIH", "Bosnia and Herzegovina", True),
    "Republic of Cameroon": ("CMR", "Cameroon", True),
    # --- Keys missed in initial draft (caught by review) ---
    "State Of Montenegro": ("MNE", "Montenegro", True),  # Case variant: "Of" not "of"
    "The Govt of the Hong Kong Spl Adm Region of the People\u2019s Republic of China": (
        "HKG",
        "Hong Kong",
        True,
    ),  # Curly apostrophe variant
}
